"""
Morphology Grid - "Carrier vs. Lifter"-style comparison figure: for each
pheromone-response mode (attractive / repulsive), samples the best few
individuals at a handful of generation checkpoints and arranges their
real MuJoCo screenshots into a side-by-side grid (rows = individuals,
columns = generations), split by mode with a vertical divider - one
figure summarizing how morphology changed over a run for each behaviour.

Uses population_history.json that main.py's evolution loop already wrote
to disk to pick individuals, and their screenshot_ind{ind_id}_assembly.png
if one is already sitting in the generation folder; any picked individual
missing one gets it regenerated by launching
`roblet_simulator.py --headless --capture_img --max_sim_time 0` against
its saved ind{ind_id}_assembly.xml, in parallel OS processes (see
SCREENSHOT_GEN_WORKERS) - no fabricated imagery, just a real (fast,
gait-free) re-render of the same evolved model.

    python plot_morphology_grid.py <output_dir> [--rows 4] [--out FILE]

<output_dir> must contain the two per-mode run folders (default names
"evolution_run" / "evolution_run_repulsive", matching main.py's
PHEROMONE_RESPONSE_TYPE-driven OUTPUT_DIR naming - see main.py's
_pheromone_suffix comment) - e.g. output_v1_0.
"""

import argparse
import json
import os
import subprocess
import sys

import numpy as np
from PIL import Image
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt

ROOT_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
_SRC_DIR = os.path.join(ROOT_DIR, "src")
if _SRC_DIR not in sys.path:
    sys.path.insert(0, _SRC_DIR)

import objectives_api as obj_api  # noqa: E402

_ROBLET_SIMULATOR = os.path.join(_SRC_DIR, "roblet_simulator.py")

THUMB_SIZE = 320  # px, square canvas each screenshot is letterboxed into
DPI = 600

N_GENERATIONS = 2  # generation checkpoints per mode (first/mid/.../last)
N_CANDIDATES_PER_GEN = 4  # individuals shown per generation column, equally
                          # spaced by scalarized fitness rank (best to worst)
                          # rather than just the top N - see _select_panel.

# Number of `roblet_simulator.py --headless --capture_img` OS processes run
# concurrently to regenerate any picked individual's missing screenshot -
# same subprocess.Popen-batch pattern as sim_executor.run_batch. Screenshot
# generation is a single fast settle-pose render (--max_sim_time 0, no gait
# simulation), so this can safely use every core.
SCREENSHOT_GEN_WORKERS = os.cpu_count() or 4
# Per-process wall-clock cap for one screenshot regen job.
SCREENSHOT_GEN_TIMEOUT_S = 120.0


def _load_population_history(run_dir):
    path = os.path.join(run_dir, "population_history.json")
    with open(path, "r", encoding="utf-8") as f:
        history = json.load(f)
    generations = sorted(history, key=lambda h: h["generation"])
    for h in generations:
        for entry in h["population"]:
            entry["objectives"] = obj_api.migrate_legacy_objectives(entry["objectives"])
    return generations


def _equally_spaced(items, n):
    """n items from `items`, evenly spaced from the first to the last
    (inclusive) rather than just the leading n - e.g. for n=3 that's
    first/middle/last. Returns all of `items` if there are <= n."""
    if len(items) <= n:
        return list(items)
    if n == 1:
        return [items[0]]
    idxs = [round(k * (len(items) - 1) / (n - 1)) for k in range(n)]
    # dedupe indices while preserving order (small input lists can collide)
    seen = set()
    idxs = [i for i in idxs if not (i in seen or seen.add(i))]
    return [items[i] for i in idxs]


def _has_population_history(run_dir):
    return os.path.exists(os.path.join(run_dir, "population_history.json"))


def _pick_checkpoint_generations(generations, n=N_GENERATIONS):
    """First, middle, and last available generation index - n=3 to match
    the reference figure's Gen-early/mid/late layout. Falls back to
    however many distinct generations actually exist if there are fewer
    than n."""
    idxs = [h["generation"] for h in generations]
    return _equally_spaced(idxs, n)


def _select_panel(run_dir, gen_checkpoints, n_rows):
    """For one mode's run_dir, picks up to n_rows individuals per
    checkpoint generation, ranked by objectives_api.scalarize (the same
    equal-weight combination the rest of the pipeline uses to pick a
    "best" individual) and equally spaced across that ranking from best
    to worst (NOT the top n_rows) - so the grid shows the spread of the
    population, not just its best performers. Filtered down to only
    individuals with a saved ind{ind_id}_assembly.xml (some fail/collide
    and never get one - see mjcf_generator/roblet_simulator), since that's
    needed to (re)render a screenshot; the screenshot itself need not
    exist yet - see _generate_screenshots.

    Returns {gen_idx: [(xml_path, screenshot_path, objectives), ...]}."""
    generations = _load_population_history(run_dir)
    by_gen = {h["generation"]: h["population"] for h in generations}
    selection = {}
    for gen_idx in gen_checkpoints:
        gen_dir = os.path.join(run_dir, f"generation_{gen_idx}")
        ranked = sorted(by_gen.get(gen_idx, []), key=lambda e: obj_api.scalarize(e["objectives"]), reverse=True)
        candidates = []
        for entry in ranked:
            ind_id = entry.get("ind_id")
            if ind_id is None:
                continue
            xml_path = os.path.join(gen_dir, f"ind{ind_id}_assembly.xml")
            if not os.path.exists(xml_path):
                continue
            screenshot_path = os.path.join(gen_dir, f"screenshot_ind{ind_id}_assembly.png")
            candidates.append((xml_path, screenshot_path, entry["objectives"]))
        selection[gen_idx] = _equally_spaced(candidates, n_rows)
    return selection


def _generate_screenshots(jobs, max_workers=SCREENSHOT_GEN_WORKERS, timeout=SCREENSHOT_GEN_TIMEOUT_S):
    """Runs `roblet_simulator.py --headless --capture_img --max_sim_time 0`
    once per (xml_path, screenshot_path) job, up to max_workers concurrent
    OS processes at a time - same subprocess.Popen-batch pattern as
    sim_executor.run_batch. --max_sim_time 0 skips the gait simulation
    entirely (just the pre-gait settle + one screenshot), so this is much
    cheaper per job than a real fitness evaluation."""
    if not jobs:
        return
    print(f"Regenerating {len(jobs)} missing screenshot(s) using up to {max_workers} parallel process(es)...")
    for batch_start in range(0, len(jobs), max_workers):
        batch = jobs[batch_start:batch_start + max_workers]
        processes = []
        for xml_path, screenshot_path in batch:
            gen_dir = os.path.dirname(xml_path)
            base = os.path.splitext(os.path.basename(xml_path))[0]
            stats_path = os.path.join(gen_dir, f"_{base}_screenshot_stats.json")
            cmd = [
                sys.executable, _ROBLET_SIMULATOR,
                "--m", xml_path, "--o", stats_path,
                "--headless", "--capture_img", "--max_sim_time", "0",
            ]
            p = subprocess.Popen(cmd, cwd=_SRC_DIR)
            processes.append((p, xml_path, stats_path))
        for p, xml_path, stats_path in processes:
            try:
                p.wait(timeout=timeout)
                if p.returncode != 0:
                    print(f"Screenshot regeneration failed (returncode={p.returncode}) for {xml_path}")
            except subprocess.TimeoutExpired:
                print(f"Screenshot regeneration timed out for {xml_path}, killing process")
                p.kill()
                p.wait()
            finally:
                try:
                    os.remove(stats_path)
                except OSError:
                    pass


def _subject_mask(arr, diff_threshold=18):
    """Boolean mask (same h,w as `arr`) marking pixels that belong to the
    robot rather than the background. A pixel counts as "subject" if it
    differs from its own row's median color by more than `diff_threshold`
    (the background is a smooth vertical gradient, so a per-row median
    tracks it at every height)."""
    row_median = np.median(arr, axis=1, keepdims=True)
    diff = np.linalg.norm(arr - row_median, axis=2)
    return diff > diff_threshold


def _content_half_extent(path, diff_threshold=18):
    """How far (in px, from the image center) the robot's silhouette
    reaches on its widest/tallest side - a MEASUREMENT only, used to size
    one shared crop window, never to crop this image individually (that
    would reintroduce per-image zoom - see _to_square_thumb). Returns
    (0, 0) if nothing clears the `_subject_mask` bar."""
    arr = np.asarray(Image.open(path).convert("RGB"), dtype=np.float32)
    h, w = arr.shape[:2]
    mask = _subject_mask(arr, diff_threshold)
    ys, xs = np.where(mask)
    if len(ys) == 0:
        return 0.0, 0.0
    cx, cy = w / 2.0, h / 2.0
    half_w = max(abs(xs.min() - cx), abs(xs.max() - cx))
    half_h = max(abs(ys.min() - cy), abs(ys.max() - cy))
    return half_w, half_h


def _shared_crop_side(paths, pad_frac=0.15):
    """One crop-window side length, shared by every thumbnail in the
    figure: big enough to fit the LARGEST robot silhouette among `paths`
    (plus padding), clamped to the source screenshots' own size. Using
    the max (not each image's own extent) is what keeps zoom level
    identical across every thumbnail - see _to_square_thumb."""
    if not paths:
        return None
    max_half = 0.0
    img_w, img_h = Image.open(paths[0]).size
    for p in paths:
        half_w, half_h = _content_half_extent(p)
        max_half = max(max_half, half_w, half_h)
    side = int(2 * max_half * (1 + pad_frac))
    return max(1, min(side, img_w, img_h))


def _to_square_thumb(path, crop_side, size=THUMB_SIZE, diff_threshold=18):
    """Crops a `crop_side`x`crop_side` window centered on the image, then
    resizes to `size`x`size`. `crop_side` is the SAME value for every
    thumbnail in the figure (see _shared_crop_side) - a fixed crop window
    plus a fixed scale factor, so a physically bigger robot still looks
    bigger in the grid instead of every thumbnail being zoomed to fill
    its own frame. The simulator's gradient background is made
    transparent (via `_subject_mask`) so each thumbnail shows only the
    robot on the figure's plain white background."""
    img = Image.open(path).convert("RGB")
    arr = np.asarray(img, dtype=np.float32)
    mask = _subject_mask(arr, diff_threshold)
    w, h = img.size
    side = min(crop_side, w, h)
    left = (w - side) // 2
    top = (h - side) // 2
    cropped = np.asarray(img.crop((left, top, left + side, top + side)))
    cropped_mask = mask[top:top + side, left:left + side]
    alpha = np.where(cropped_mask, 255, 0).astype(np.uint8)
    rgba = np.dstack([cropped, alpha])
    return Image.fromarray(rgba, mode="RGBA").resize((size, size), Image.LANCZOS)


def _draw_mode_panel(fig, gs_slice, selection, gen_checkpoints, mode_label, n_rows, crop_side):
    n_cols = len(gen_checkpoints)
    axes = gs_slice.subgridspec(n_rows, n_cols, hspace=0.06, wspace=0.06).subplots(squeeze=False)
    for col, gen_idx in enumerate(gen_checkpoints):
        picks = selection.get(gen_idx, [])
        for row in range(n_rows):
            ax = axes[row, col]
            ax.set_xticks([])
            ax.set_yticks([])
            for spine in ax.spines.values():
                spine.set_visible(False)
            screenshot_path = picks[row][1] if row < len(picks) else None
            if screenshot_path and os.path.exists(screenshot_path):
                thumb = _to_square_thumb(screenshot_path, crop_side)
                ax.imshow(thumb)
            else:
                ax.set_facecolor("#f2f2f2")
        axes[-1, col].set_xlabel(f"Gen {gen_idx}", fontsize=11, labelpad=6)
    axes[0, n_cols // 2].set_title(mode_label, fontsize=16, fontweight="bold", pad=14)


def build_morphology_grid(output_dir, attractive_dir="evolution_run",
                           repulsive_dir="evolution_run_repulsive",
                           n_rows=N_CANDIDATES_PER_GEN, n_gens=N_GENERATIONS, out_path=None):
    modes = [("Attractive", os.path.join(output_dir, attractive_dir))]
    repulsive_path = os.path.join(output_dir, repulsive_dir)
    if _has_population_history(repulsive_path):
        modes.append(("Repelling", repulsive_path))
    else:
        print(f"No population_history.json under '{repulsive_path}' - building a single-panel "
              f"figure (attractive only).")

    panels = []  # (label, gen_checkpoints, selection)
    for label, run_dir in modes:
        gens = _pick_checkpoint_generations(_load_population_history(run_dir), n_gens)
        panels.append((label, gens, _select_panel(run_dir, gens, n_rows)))

    # Regenerate every picked individual's screenshot that isn't already on
    # disk, in one shared batch across EVERY panel/generation (not one
    # batch per panel) so SCREENSHOT_GEN_WORKERS processes stay busy across
    # the whole figure's worth of work at once.
    missing = [
        (xml_path, screenshot_path)
        for _, _, selection in panels
        for picks in selection.values()
        for xml_path, screenshot_path, _ in picks
        if not os.path.exists(screenshot_path)
    ]
    _generate_screenshots(missing)

    # One crop window shared by EVERY thumbnail in the whole figure (every
    # panel) - sized to the largest robot found anywhere in the figure - so
    # zoom level is identical across modes and generations, not just within
    # a single panel.
    all_paths = [
        screenshot_path
        for _, _, selection in panels
        for picks in selection.values()
        for _, screenshot_path, _ in picks
        if os.path.exists(screenshot_path)
    ]
    crop_side = _shared_crop_side(all_paths)

    fig = plt.figure(figsize=(3.1 * n_gens * len(panels) + 1.0, 3.3 * n_rows))
    outer = fig.add_gridspec(1, len(panels), wspace=0.10)

    for col, (label, gens, selection) in enumerate(panels):
        _draw_mode_panel(fig, outer[0, col], selection, gens, label, n_rows, crop_side)

    if len(panels) > 1:
        # Vertical divider between mode panels, matching the reference
        # figure's dashed center line.
        fig.add_artist(plt.Line2D([0.5, 0.5], [0.03, 0.94], transform=fig.transFigure,
                                   color="#333333", linestyle="--", linewidth=1.2))
    fig.suptitle("Evolved Morphology Across Generations by Pheromone Response Mode",
                 fontsize=15, fontweight="bold", y=0.99)

    out_path = out_path or os.path.join(output_dir, "morphology_grid.png")
    fig.savefig(out_path, dpi=DPI, bbox_inches="tight")
    plt.close(fig)
    return out_path


def main():
    parser = argparse.ArgumentParser(description="Build a Carrier/Lifter-style morphology comparison grid.")
    parser.add_argument("output_dir", nargs="?", default=os.path.join(ROOT_DIR, "output"),
                         help="Folder containing the attractive/repulsive run subfolders "
                              "(default: <repo_root>/output, regardless of current directory)")
    parser.add_argument("--attractive_dir", default="evolution_run")
    parser.add_argument("--repulsive_dir", default="evolution_run_repulsive")
    parser.add_argument("--rows", type=int, default=N_CANDIDATES_PER_GEN,
                         help="Individuals shown per generation column, equally spaced by scalarized fitness rank")
    parser.add_argument("--gens", type=int, default=N_GENERATIONS,
                         help="Generation checkpoints per mode (first/mid/.../last)")
    parser.add_argument("--out", default=None, help="Output PNG path (default: <output_dir>/morphology_grid.png)")
    args = parser.parse_args()

    path = build_morphology_grid(
        args.output_dir, attractive_dir=args.attractive_dir, repulsive_dir=args.repulsive_dir,
        n_rows=args.rows, n_gens=args.gens, out_path=args.out,
    )
    print(f"Saved: {path}")


if __name__ == "__main__":
    main()
