"""
Roblet Simulator - A simulation environment for testing self folding and
magnetic actuation of microrobots using MuJoCo physics engine.
"""

# pylint: disable=no-member

import json
import os
import time
import mujoco
import mujoco.viewer
import numpy as np

# Global dictionaries mapping Parent Body ID -> List of (Magnet Geom ID, Polarity Sign)
parent_body_magnet_map = {}

# Torque tracking global variables
torque_history = []

# Physics constants
# Magnetic field intensity (Tesla)
B_INTENSITY = 0.01  # 10 mT
# 6.5 x 10^-3 Am^2 - 2mm x 2mm neodymium magnet cylinder (N42SH)
M_MOMENT = 6.5e-3
# Maximum torque multiplier
TORQUE_MULTIPLIER = 10
# Time taken to reach full torque
TORQUE_RAMP_TIME = 10  # seconds
FREQUENCY = 6.25  # Hz

# Rangefinder reading (m) below which a wall is considered "reached".
WALL_STOP_DISTANCE = 200  # 200 mm

# Wall geoms are tagged group=1 in the model (see mjcf_generator.py) so this
# raycast can be filtered to see ONLY them.
_WALL_GEOMGROUP = np.zeros(6, dtype=np.uint8)
_WALL_GEOMGROUP[1] = 1


def magnetic_field_callback(model, data):
    """
    MuJoCo Control Callback.
    Calculates magnetic torque:
        Tau = M x B
    Applies torque to parent module bodies and records net applied torque magnitude.
    """
    # Clear previous external forces
    data.xfrc_applied.fill(0)
    # Smooth torque ramp
    ramp_progress = min(data.time / TORQUE_RAMP_TIME, 1.0)
    # Smoothstep: f(x)=x^2*(3−2x)
    # 0 -> 1 with zero slope at start and end
    ramp_factor = ramp_progress * ramp_progress * (3 - 2 * ramp_progress)
    effective_torque_multiplier = TORQUE_MULTIPLIER * ramp_factor


    # Oscillating magnetic field along Z-axis (vertical) to induce walking motion.
    # It flips sign along a single fixed vertical axis at frequency f:
    #   Phase 1 (B = -z): torque pitches the robot forward about its front foot.
    #   Phase 2/3 (B = +z): torque lifts the front foot, robot rotates about its
    #   COM and lands back on its rear foot.
    # Half-period = 1/(2f) per the paper's t1 = 1/(2f).
    total_cycle_time = 1.0 / FREQUENCY
    half_cycle_time = total_cycle_time / 2.0
    time_in_cycle = data.time % total_cycle_time

    b_z = -B_INTENSITY if time_in_cycle < half_cycle_time else B_INTENSITY

    # Magnetic field along Z only
    b_vector = np.array([0.0, 0.0, b_z])

    step_total_torque = 0.0

    # Apply magnetic torque
    for parent_body_id, magnet_list in parent_body_magnet_map.items():
        accumulated_torque = np.zeros(3)
        for geom_id, polarity_sign in magnet_list:
            # Magnet world orientation
            geom_mat = data.geom_xmat[geom_id].reshape(3, 3)
            # Magnet dipole along local Z-axis
            local_m = np.array([0.0, 0.0, 1.0]) * M_MOMENT * polarity_sign
            # Convert dipole to world frame
            world_m = geom_mat.dot(local_m)
            # Tau = M x B
            torque_vector = np.cross(world_m, b_vector)
            accumulated_torque += torque_vector

        ramped_torque = accumulated_torque * effective_torque_multiplier
        data.xfrc_applied[parent_body_id][3:6] = ramped_torque
        step_total_torque += ramped_torque

    # Record magnitude of total torque on whole body for this step
    torque_history.append(np.linalg.norm(step_total_torque))


def find_main_movable_parent(model, body_id):
    """Traces up the MuJoCo body tree to find the main movable module body."""
    current_id = body_id
    while current_id != 0:
        parent_id = model.body_parentid[current_id]
        if parent_id == 0:
            return current_id
        current_id = parent_id
    return body_id


def find_all_magnets(model):
    """Finds all magnets in the model and maps parent body ID to magnets."""
    magnet_map = {}
    for geom_id in range(model.ngeom):
        geom_name = mujoco.mj_id2name(model, mujoco.mjtObj.mjOBJ_GEOM, geom_id)
        if geom_name and "magnet_" in geom_name:
            immediate_body_id = model.geom_bodyid[geom_id]
            movable_parent_id = find_main_movable_parent(model, immediate_body_id)
            polarity_sign = 1.0 if "SGA" in geom_name else -1.0
            if movable_parent_id not in magnet_map:
                magnet_map[movable_parent_id] = []
            magnet_map[movable_parent_id].append((geom_id, polarity_sign))
    return magnet_map


def find_module_labels(model):
    """Scans model's bodies to map top-level module IDs to their names."""
    module_labels = {}
    for body_id in range(model.nbody):
        body_name = mujoco.mj_id2name(model, mujoco.mjtObj.mjOBJ_BODY, body_id)
        # Identify main module wrappers generated by the assembly builder script
        if body_name and body_name.startswith("module_"):
            module_labels[body_id] = body_name
    return module_labels


def set_angle_to_joint(model, data, target_angle_deg):
    """Sets actuator position targets."""
    if model.nu == 0:
        return

    target_rad = np.radians(abs(target_angle_deg))

    for i in range(model.nu):
        lo, hi = model.actuator_ctrlrange[i]

        # Target falls inside positive range (Valley fold)
        if lo >= 0 and lo <= target_rad <= hi:
            data.ctrl[i] = target_rad
        # Target falls inside negative range (Mountain fold)
        elif hi <= 0 and lo <= -target_rad <= hi:
            data.ctrl[i] = -target_rad
        else:
            lo_deg, hi_deg = np.degrees(lo), np.degrees(hi)
            raise ValueError(
                f"Target {target_angle_deg}° (or -{target_angle_deg}°) is out "
                f"of bounds for actuator {i} range [{lo_deg:.1f}°, {hi_deg:.1f}°]"
            )


def distance_to_nearest_wall(model, data):
    """Minimum of the 4 wall-facing rangefinder rays (m), or None if none of
    them currently hit a wall.

    Uses a manual, geom-group-filtered mj_ray() rather than a native
    <rangefinder> sensor: the native sensor only excludes the ray site's own
    body, so as module_1 pitches through the flip gait it would "see" the
    floor or a neighboring welded module (only ~8mm away) as a hit. Filtering
    to geom group 1 (the walls only) makes those false positives impossible.
    """
    geomid = np.zeros(1, dtype=np.int32)
    readings = []
    for wall_dir in ("north", "south", "east", "west"):
        site_id = mujoco.mj_name2id(model, mujoco.mjtObj.mjOBJ_SITE, f"rf_{wall_dir}")
        pnt = data.site_xpos[site_id]
        vec = data.site_xmat[site_id].reshape(3, 3)[:, 2]
        dist = mujoco.mj_ray(model, data, pnt, vec, _WALL_GEOMGROUP, True, -1, geomid)
        if dist >= 0:
            readings.append(dist)
    return min(readings) if readings else None


def get_com_position(data):
    """World-frame center of mass position of the whole model (m)."""
    return data.subtree_com[0].copy()


def get_com_velocity(data):
    """World-frame linear velocity of the whole model's center of mass (m/s).

    subtree_linvel is not populated by mj_step on its own - it requires an
    explicit mj_subtreeVel(model, data) call each step (unless a
    subtreelinvel sensor is defined in the XML).
    """
    return data.subtree_linvel[0].copy()


def dynamic_text_rendering(viewer, data, module_labels):
    """
    Dynamically renders text labels for each module body in the simulation.
    """
    # Reset custom user scene geoms at the start of each frame
    viewer.user_scn.ngeom = 0

    for body_id, label_text in module_labels.items():
        # Fetch position of the module body
        pos = data.xpos[body_id].copy()

        # Height offset: 0.0003 m (0.3 mm) so the label floats clearly above the module
        pos[2] += 0.0003

        # Fetch reference to current visual geom slot
        geom = viewer.user_scn.geoms[viewer.user_scn.ngeom]

        # Call mjv_initGeom using positional arguments
        mujoco.mjv_initGeom(
            geom,
            mujoco.mjtGeom.mjGEOM_LABEL,
            np.array([0.005, 0.005, 0.005], dtype=np.float64),
            pos.astype(np.float64),
            np.eye(3).flatten().astype(np.float64),
            np.array([1.0, 1.0, 1.0, 1.0], dtype=np.float32),  # White label text
        )

        # Assign label string (displays "1", "2", "3", etc.)
        display_tag = label_text.split("_")[-1]
        geom.label = display_tag

        viewer.user_scn.ngeom += 1


def save_simulation_stats(model, avg_velocity, total_distance, module_labels, filename="simulation_stats.json"):
    """Calculates masses and average torque, then saves to a JSON file."""
    # Total mass of the whole model
    total_mass = float(mujoco.mj_getTotalmass(model))

    # Mass of each individual module body tree
    module_masses = []
    for body_id in sorted(module_labels.keys()):
        # body_subtreemass includes the body and all child geoms/bodies attached to it
        module_mass = float(model.body_subtreemass[body_id])
        module_masses.append({
            "module_id": module_labels[body_id],
            "mass_mg": round(module_mass * 1e6, 4)  # Convert to milligrams
        })

    # Average torque acting on whole body across all physics steps
    avg_torque = float(np.mean(torque_history)) if torque_history else 0.0

    stats = {
        "total_mass_mg": round(total_mass * 1e6, 4),  # Convert to milligrams
        "module_masses_mg": module_masses,
        "average_torque_Nm": round(avg_torque, 4),  # Convert to Newton-meters
        "total_simulated_steps": len(torque_history),
        "average_velocity_mmps": round(avg_velocity * 1000, 4),
        "total_distance_mm": round(total_distance * 1000, 4),
    }

    with open(filename, "w", encoding="utf-8") as f:
        json.dump(stats, f, indent=4)

    print(f"\nSaved simulation statistics to '{filename}':")
    print(f" - Total Mass: {total_mass * 1e6:.2f} mg")
    print(f" - Average Torque: {avg_torque:.2e} N·m")
    print(f" - Last Torque: {torque_history[-1]:.2e} N·m")
    print(f" - Average velocity: {avg_velocity * 1000:.2f} mm/s")
    print(f" - Total Distance: {total_distance * 1000:.2f} mm")

def main():
    """Load the MuJoCo model, initialize magnets, and run the simulation."""
    model_path = "../models/assembly.xml"
    if not os.path.exists(model_path):
        print(f"Error: Could not find '{model_path}'")
        return
    print(f"Loading model: {model_path}...")

    model = mujoco.MjModel.from_xml_path(model_path)
    data = mujoco.MjData(model)

    # Simulation timestep
    model.opt.timestep = 0.01  # 10 milliseconds

    # Find all magnets
    parent_body_magnet_map.clear()
    parent_body_magnet_map.update(find_all_magnets(model))

    # Identify module bodies and assign their text labels
    module_labels = find_module_labels(model)

    # Register callback
    mujoco.set_mjcb_control(magnetic_field_callback)

    dt = model.opt.timestep

    with mujoco.viewer.launch_passive(model, data) as viewer:
        viewer.cam.distance = 0.25  # zoom
        viewer.cam.lookat[:] = [0, 0, 0]
        last_print = -1
        avg_velocity = 0.0
        initial_com = None
        displacement = 0.0
        # Displacement captured the instant the torque ramp finishes, so the
        # ramp's slow-moving first TORQUE_RAMP_TIME seconds can be excluded
        # from the average velocity below.
        steady_state_displacement = None
        magnets_active = True

        while viewer.is_running():
            step_start = time.time()
            set_angle_to_joint(model, data, target_angle_deg=45)

            mujoco.mj_step(model, data)
            mujoco.mj_subtreeVel(model, data)

            # Ground-truth morphology performance metrics, tracked from the
            # whole-model subtree COM (body 0 = worldbody subtree = everything).
            # Gated on magnets_active so these freeze at the wall-stop instant
            # instead of draining toward 0 during whatever idle time passes
            # in the viewer after locomotion has actually ended.
            if magnets_active:
                com = get_com_position(data)
                if initial_com is None:
                    initial_com = com.copy()

                displacement = float(np.linalg.norm(com - initial_com))

                # Average velocity is calculated from the displacement after the torque ramp finishes.
                if steady_state_displacement is None and data.time >= TORQUE_RAMP_TIME:
                    steady_state_displacement = displacement
                if steady_state_displacement is not None:
                    steady_elapsed = data.time - TORQUE_RAMP_TIME
                    avg_velocity = (
                        (displacement - steady_state_displacement) / steady_elapsed
                        if steady_elapsed > 0 else 0.0
                    )

            # Stop actuating once the assembly gets close to a wall, judged
            # from the on-body rangefinders (not a ground-truth position
            # check) - mirrors a real obstacle-avoidance cutoff.
            if magnets_active:
                wall_dist = distance_to_nearest_wall(model, data)
                if wall_dist is not None:
                    wall_dist *= 1000  # Convert to mm
                if wall_dist is not None and wall_dist < WALL_STOP_DISTANCE:
                    mujoco.set_mjcb_control(None)
                    # xfrc_applied is a persistent array, not reset by
                    # unregistering the callback - without this the last
                    # applied torque would keep acting on every future step.
                    data.xfrc_applied.fill(0)
                    magnets_active = False
                    print(f"Time: {data.time:.2f}s | Wall reached ({int(wall_dist)}) mm) - magnetic field stopped.")

            # Render dynamic text labels for each module
            #dynamic_text_rendering(viewer, data, module_labels)

            viewer.sync()

            # Print torque ramp progress and body velocity every second
            current_second = int(data.time)
            if current_second != last_print and magnets_active :
                last_print = current_second
                ramp = min(data.time / TORQUE_RAMP_TIME, 1.0)
                if ramp < 1.0:
                    print(
                        f"Time: {data.time:.2f}s | Torque ramp: {int(ramp*100)}%"
                    )
                else:
                    print(
                        f"Avg velocity: {avg_velocity * 1000:.2f} mm/s | "
                        f"Displacement: {displacement * 1000:.2f} mm"
                    )

            # Maintain real-time velocity
            time_until_next_step = dt - (time.time() - step_start)
            if time_until_next_step > 0:
                time.sleep(time_until_next_step)

    # Unregister callback and save JSON data on exit
    mujoco.set_mjcb_control(None)
    save_simulation_stats(model, avg_velocity, displacement, module_labels, filename="../output/simulation_stats.json")


if __name__ == "__main__":
    main()